version: '3.7'

services:
  vuero-demo:
    image: digisquad/cssninja.vuero-demo:latest
    networks:
      - cssninja-services
    restart: '${MOEBIUS_DEMO_RESTART:-no}'
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.vuero-demo.entrypoints: 'http'
      traefik.http.routers.vuero-demo.rule: 'Host(`vuero.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.vuero-demo.middlewares: 'https-redirect@file'
      traefik.http.routers.vuero-demo.service: 'vuero-demo-https'
      traefik.http.services.vuero-demo-https.loadbalancer.server.port: 5000
      traefik.http.routers.vuero-demo-https.rule: 'Host(`vuero.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.vuero-demo-https.tls: true
      traefik.http.routers.vuero-demo-https.entrypoints: 'https'
      traefik.http.routers.vuero-demo-https.tls.certresolver: 'http'
      traefik.http.routers.vuero-demo-https.service: 'vuero-demo-https'
      traefik.http.routers.vuero-api.entrypoints: 'http'
      traefik.http.routers.vuero-api.rule: 'Host(`api.vuero.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.vuero-api.middlewares: 'https-redirect@file'
      traefik.http.routers.vuero-api.service: 'vuero-api-https'
      traefik.http.services.vuero-api-https.loadbalancer.server.port: 8080
      traefik.http.routers.vuero-api-https.rule: 'Host(`api.vuero.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.vuero-api-https.tls: true
      traefik.http.routers.vuero-api-https.entrypoints: 'https'
      traefik.http.routers.vuero-api-https.tls.certresolver: 'http'
      traefik.http.routers.vuero-api-https.service: 'vuero-api-https'

networks:
  cssninja-services:
    external: true
