// import { createApp } from 'vue'
import { ViteSSG } from 'vite-ssg'
// import routes generated by Voie
import routes from 'voie-pages'
import installPlugins from './plugins'
import App from './App.vue'

export const createApp = ViteSSG(
  // the root component
  App,
  // vue-router options
  { routes },
  // function to have custom setups
  (context) => {
    installPlugins(context)
  }
)
