import { createApp } from 'vue'
// import routes generated by vite-plugin-pages
// import routes from 'voie-pages'
import installPlugins from './plugins'
import App from './App.vue'

// console.log('routes', routes)

const app = createApp(App)
installPlugins(app)
app.mount('#app')

// export const createApp = ViteSSG(
//   // the root component
//   App,
//   // vue-router options
//   { routes },
//   // function to have custom setups
//   (context) => {
//     installPlugins(context)
//   }
// )
