name: deploy
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.vscode/**'
      - 'cypress/**'
      - 'scripts/**'
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml

  docker-build:
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - uses: actions/checkout@v4
      - name: Set up dockertags
        run: |
          echo "dockertags=digisquad/cssninja.vuero-demo:latest" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        timeout-minutes: 60
        with:
          push: true
          tags: ${{ env.dockertags }}
          build-args: |
            VITE_API_BASE_URL=https://vuero-api.cssninja.io
            GTM_ID=GTM-N9P6H6B

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.yml
          target: ${{ secrets.HOST_DIRECTORY }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.HOST_DIRECTORY }}
            docker-compose pull
            docker-compose up -d --force-recreate --remove-orphans
            docker image prune -f -a --filter "until=24h"
