name: deploy-edge
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/**'
      - 'packages/demo/**'
    branches:
      - edge

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Set up dockertags
        run: |
          echo "dockertags=digisquad/cssninja.vuero-demo:edge" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        timeout-minutes: 60
        with:
          context: ./packages/demo
          push: true
          tags: ${{ env.dockertags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_BASE_URL=https://vuero-edge-api.cssninja.io

  deploy:
    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - uses: actions/checkout@v6
      - name: Publish
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          target: ${{ secrets.HOST_DIRECTORY_EDGE }}
          source: .github/env/edge/docker-compose.yml
          strip_components: 3

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd ${{ secrets.HOST_DIRECTORY_EDGE }}
            docker compose pull
            docker compose up -d --force-recreate --remove-orphans
            docker image prune -f -a --filter "until=24h"
