name: release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed for git history

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - id: meta
        name: release meta
        run: |
          project=${GITHUB_REPOSITORY#*/}
          echo "PROJECT=${project}" >> "$GITHUB_OUTPUT"
          echo "PROJECT_CAP=${project^}" >> "$GITHUB_OUTPUT"
          echo "TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"

      - id: build_template
        name: build release template
        uses: ./.github/actions/build-template-action
        with:
          tag: ${{ steps.meta.outputs.TAG }}
          project: ${{ steps.meta.outputs.PROJECT }}

      - id: build_quickstarter
        name: build release quickstarter
        uses: ./.github/actions/build-quickstarter-action
        with:
          tag: ${{ steps.meta.outputs.TAG }}
          project: ${{ steps.meta.outputs.PROJECT }}

      - id: changelog
        name: release changelog
        run: |
          pnpm dlx conventional-changelog-cli -p conventionalcommits -r 2 -o ${{ github.workspace }}/CHANGELOG_RELEASE.md
          cat ${{ github.workspace }}/CHANGELOG_RELEASE.md

      - id: create_release
        name: create github draft release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.meta.outputs.TAG }}
          name: ${{ steps.meta.outputs.PROJECT_CAP }} ${{ steps.meta.outputs.TAG }}
          body_path: ${{ github.workspace }}/CHANGELOG_RELEASE.md
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            ${{ github.workspace }}/${{ steps.build_template.outputs.filepath }}
            ${{ github.workspace }}/${{ steps.build_quickstarter.outputs.filepath }}

      - name: publish github draft release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.APP_GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
