name: tests-quickstarter

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        package: [app, app-ssr, app-electron, app-nuxt, demo]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: corepack enable
      
      - id: build_app
        name: build archive
        uses: ./.github/actions/build-template-action
        with:
          tag: test
          project: vuero
          package: ${{ matrix.package }}

      - name: extract quickstarter
        run: |
          unzip ${{ steps.build_app.outputs.filepath }} -d ${{ github.workspace }}/temp

      - name: install quickstarter
        working-directory: ./temp
        run: |
          pnpm --ignore-workspace install

      - name: test quickstarter
        working-directory: ./temp
        run: |
          pnpm test
      
      - name: build quickstarter
        working-directory: ./temp
        run: |
          NODE_OPTIONS=--max_old_space_size=4096 pnpm build
