name: tests-e2e

on:
  workflow_call:

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome107
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: cypress-io/github-action@v4
        with:
          # record: true
          # parallel: true
          install: true
          build: pnpm ssr:build
          start: pnpm ssr:preview
          command: pnpm test:e2e --headless --browser chrome
          wait-on: 'http://localhost:3000'
          cache-key: ${{ matrix.node-version }}-${{ runner.os }}-cypress-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
