name: tests-e2e

on:
  workflow_call:

jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: cypress-io/github-action@v4
        with:
          # record: true
          # parallel: true
          install: true
          build: pnpm build
          start: pnpm preview
          command: pnpm test:e2e
          wait-on: 'http://localhost:5000'
          cache-key: ${{ matrix.node-version }}-${{ runner.os }}-cypress-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
