name: tests-quickstarter

on:
  workflow_call:
  workflow_dispatch:

jobs:
  quickstarter-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: corepack enable
      
      - id: build_quickstarter
        name: build test quickstarter
        uses: ./.github/actions/build-quickstarter-action
        with:
          tag: test
          project: vuero

      - name: extract quickstarter
        run: |
          unzip ${{ github.workspace }}/${{ steps.build_quickstarter.outputs.filepath }} -d ${{ github.workspace }}/quickstarter

      - name: install quickstarter
        working-directory: ./quickstarter
        run: |
          pnpm install
      
      - name: build quickstarter
        working-directory: ./quickstarter
        run: |
          pnpm build

  quickstarter-build-ssr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: corepack enable
      
      - id: build_quickstarter
        name: build test quickstarter
        uses: ./.github/actions/build-quickstarter-action
        with:
          tag: test
          project: vuero

      - name: extract quickstarter
        run: |
          unzip ${{ github.workspace }}/${{ steps.build_quickstarter.outputs.filepath }} -d ${{ github.workspace }}/quickstarter

      - name: install quickstarter
        working-directory: ./quickstarter
        run: |
          pnpm install
      
      - name: build quickstarter (ssr)
        working-directory: ./quickstarter
        run: |
          pnpm ssr:build

  quickstarter-build-ssg:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - run: corepack enable
      
      - id: build_quickstarter
        name: build test quickstarter
        uses: ./.github/actions/build-quickstarter-action
        with:
          tag: test
          project: vuero

      - name: extract quickstarter
        run: |
          unzip ${{ github.workspace }}/${{ steps.build_quickstarter.outputs.filepath }} -d ${{ github.workspace }}/quickstarter

      - name: install quickstarter
        working-directory: ./quickstarter
        run: |
          pnpm install
      
      - name: build quickstarter (ssg)
        working-directory: ./quickstarter
        run: |
          pnpm ssg:build
        